export const SAVE_LOCATION = 'SAVE_LOCATION';
export const LOAD_INFORMATION = 'LOAD_INFORMATION';
export const LOAD_LOCALISATION = 'LOAD_LOCALISATION';
export const SAVE_MYLOCALISATION = 'SAVE_MYLOCALISATION';
